export const STRINGS = {
  title: "Vei participa?",
  description: "Te așteptăm cu drag!",
  description2: "Completează formularul de mai jos pentru",
  description22: "a ne anunța răspunsul tău.",
  description3: "Te rugăm să ne comunici răspunsul tău până",
  description33: "la data de 10 septembrie 2025.",
  eventDate: "2025-09-27",
  eventLocation: `Event Park @Lagoo Snagov, 44°41'21.6"N 26°09'45.6"E, 077165`,
  nameLabel: "Nume",
  emailLabel: "Email",
  accompanyLabel: "Număr de persoane",
  detailsLabel: "Alte observații",
  noOption: "Nu pot să particip",
  submitButton: "Confirm prezența",
  thankYouMessage: "Multumim pentru raspuns!",
  viewOnMapButton: "Vezi locație pe Google Maps",
  sendFromEmail: "onboarding@resend.dev",
  sendToEmail: process.env.EMAIL_TO,
  location: "Locații",
  whereAndWhen: "UNDE ȘI CÂND",
  parents: "Cu binecuvântarea părinților",
  parentsName: "Maria și Marian & Laura și Teodor",
  godParents: "Și împreună cu nașii noștri",
  godParentsName: "Cristina și Radu & Monica și Vasile",
  church: "CUNUNIA RELIGIOASĂ",
  churchLabel: "Sâmbătă, 27 septembrie 2025, 14:00",
  churchLocation: "Biserica Domnească „Sfântul Gheorghe”",
  churchLocation2: "\"Saint George\" Church, Pitești",
  party: "PETRECEREA",
  partyLabel: "Sâmbătă, 27 septembrie 2025, 19:00",
  partyLocation: "Aria Events (Complex Slava)",
  partyLocation2: `Aria Events - Restaurant pentru evenimente Pitești`,
  menuLabel: "Tip meniu",
  menuSelect: "Selectează tipul de meniu",
  menuStandard: "Meniu standard",
  menuVegetarian: "Meniu vegetarian",
  menuVegan: "Meniu vegan",
  section1: "Vă așteptăm să ne fiți alături",
  section2: "la nunta noastră din",
  section3: "27 Septembrie 2025",
};
