export const STRINGS = {
  title: "Vei participa?",
  description: "Te așteptăm cu drag!",
  description2: "Completează formularul de mai jos pentru",
  description22: "a ne anunța decizia ta.",
  description3: "Te rugăm să ne comunici decizia ta până",
  description33: "la data de 1 iulie 2025.",
  eventDate: "2025-08-23",
  eventLocation: `Event Park @Lagoo Snagov, 44°41'21.6"N 26°09'45.6"E, 077165`,
  nameLabel: "Nume",
  emailLabel: "Email",
  accompanyLabel: "Număr de persoane",
  detailsLabel: "Alte observații",
  noOption: "Nu pot să particip",
  submitButton: "Confirm prezența",
  thankYouMessage: "Multumim pentru raspuns!",
  viewOnMapButton: "Vezi locație pe Google Maps",
  sendFromEmail: "onboarding@resend.dev",
  sendToEmail: process.env.EMAIL_TO,
  location: "Locații",
  whereAndWhen: "UNDE ȘI CÂND",
  parents: "Cu binecuvântarea părinților",
  parentsName: "Manuela și Cristian & Mioara și Valentin",
  godParents: "Și împreună cu nașii noștri",
  godParentsName: "Cristina și Andrei",
  church: "CUNUNIA RELIGIOASA",
  churchLabel: "Sâmbătă, 23 august 2025, 15:00",
  churchLocation: "Biserica Sfântul Antonie",
  churchLocation2: "Strada Jean Steriadi 19A, București",
  party: "PETRECEREA",
  partyLabel: "Sâmbătă, 23 august 2025, 19:30",
  partyLocation: "Lagoo Snagov, Pavilion Sole",
  partyLocation2: `Strada Plopilor, nr. 1, Comuna Snagov`,
  menuLabel: "Tip meniu",
  menuSelect: "Selectează tipul de meniu",
  menuStandard: "Meniu standard",
  menuVegetarian: "Meniu vegetarian",
  section1: "Vă așteptăm să ne fiți alături",
  section2: "la nunta noastră din",
  section3: "23 August 2025",
};
