export const STRINGS = {
  title: "Invitație online pentru nuntă",
  description:
    "Suntem incantati sa va avem alaturi de noi in ziua nuntii noastre. Va rugam sa completati formularul de mai jos pentru a confirma prezenta.",
  eventDate: "2025-08-23",
  eventDateLabel: "Data evenimentului",
  eventLocation: `Event Park @Lagoo Snagov, 44°41'21.6"N 26°09'45.6"E, 077165`,
  nameLabel: "Nume",
  emailLabel: "Email",
  accompanyLabel: "Număr de persoane",
  noOption: "Nu pot să particip",
  submitButton: "Confirm prezența",
  thankYouMessage: "Multumim pentru raspuns!",
  viewOnMapButton: "Vezi locatie pe Google Maps",
  sendFromEmail: "onboarding@resend.dev",
  sendToEmail: process.env.EMAIL_TO,
  parents: "Cu binecuvântarea părinților",
  parentsName: "Manuela și Cristian & Mioara și Valentin",
  godParents: "Și împreună cu nașii noștri",
  godParentsName: "Cristina și Andrei",
  church: "CUNUNIA RELIGIOASA",
  churchLabel: "Sâmbătă, 23 august 2025, 15:00",
  churchLocation: "Biserica Sfântul Antonie",
  churchLocation2: "Strada Jean Steriadi 19A, București",
  party: "PETRECEREA",
  partyLabel: "Sâmbătă, 23 august 2025, 19:30",
  partyLocation: "Lagoo Snagov, Pavilion Sole",
  partyLocation2: `Strada Plopilor, nr. 1, Comuna Snagov`,
  menuLabel: "Tip meniu",
  menuSelect: "Selectează tipul de meniu",
  menuStandard: "Meniu standard",
  menuVegetarian: "Meniu vegetarian",
};
